import {
  Microservice,
  ServiceDependency,
  MetricDataPoint,
  LogEntry,
  AnomalyRecord,
  Incident,
  RcaCandidate,
  RemediationPlaybook,
  RemediationRecommendation,
  ApprovalAction,
  FaultScenarioType,
  FaultScenarioMeta,
} from '../types';

export const FAULT_SCENARIOS: FaultScenarioMeta[] = [
  {
    id: 'normal',
    title: 'Normal Operational Baseline',
    targetService: 'All Services',
    category: 'Nominal',
    description: 'All 5 microservices running within nominal baseline thresholds with healthy response times and low error rates.',
    telemetrySignatures: ['CPU < 35%', 'Latency p95 < 45ms', 'Error rate < 0.2%', 'DB query < 15ms'],
    expectedTopRootCause: 'System Healthy (No active incident)',
    recommendedPlaybook: 'Routine Observability Monitoring',
    safeRecoveryAction: 'None needed',
  },
  {
    id: 'cpu_saturation_order',
    title: 'CPU Saturation in Order Service',
    targetService: 'Order Service',
    category: 'Compute Overload',
    description: 'Unbounded loop and heavy deserialization in Order processing pipeline causes severe CPU saturation (96%), latency spike, and order timeouts.',
    telemetrySignatures: ['Order CPU 96%', 'Latency p95 > 1400ms', 'Error rate 18.5%', 'Order queue backlog > 450'],
    expectedTopRootCause: 'Order Service CPU compute saturation due to unoptimized batch serialization loop',
    recommendedPlaybook: 'Scale Out Order Service & Throttle Processing',
    safeRecoveryAction: 'Scale replica +1 and deploy compute throttle',
  },
  {
    id: 'memory_leak_user',
    title: 'Memory Leak in User Service',
    targetService: 'User Service',
    category: 'Resource Exhaustion',
    description: 'Unbounded session token retention cache causes steady memory expansion (92% heap), frequent garbage collection pauses, and degradation.',
    telemetrySignatures: ['User Memory 940MB / 1024MB', 'GC pauses > 350ms', 'Latency p95 890ms', 'OOM risk warning'],
    expectedTopRootCause: 'User Service memory leak in active session token retention cache',
    recommendedPlaybook: 'Hot Restart Instance & Reset Session Cache',
    safeRecoveryAction: 'Graceful instance restart & session cache flush',
  },
  {
    id: 'database_latency_order',
    title: 'Database Latency & Slow Query',
    targetService: 'Order Service & PostgreSQL',
    category: 'Database Bottleneck',
    description: 'Missing composite index on orders table triggers full table scans on large volumes, driving DB CPU to 92% and slowing all dependent reads/writes.',
    telemetrySignatures: ['DB Query Latency 1850ms', 'PostgreSQL CPU 91%', 'Order latency 2100ms', 'Lock wait time 820ms'],
    expectedTopRootCause: 'PostgreSQL slow full-table scan on unindexed orders query',
    recommendedPlaybook: 'Add Composite Index & Enable Query Cache',
    safeRecoveryAction: 'Enable temporary read cache & add recommended index',
  },
  {
    id: 'db_connection_exhaustion',
    title: 'Database Connection Pool Exhaustion',
    targetService: 'Payment Service & PostgreSQL',
    category: 'Connection Leak',
    description: 'Leaked database connections in payment transaction handler max out the connection pool (98/100 active), causing connection timeouts.',
    telemetrySignatures: ['DB Connections 98/100', 'Connection timeout errors > 32/min', 'Payment failure rate 24%'],
    expectedTopRootCause: 'Payment Service DB connection pool exhaustion from unclosed transactional sessions',
    recommendedPlaybook: 'Force Close Leaked Connections & Resize Pool',
    safeRecoveryAction: 'Recycle idle connection pool & expand temporary headroom',
  },
  {
    id: 'service_crash_payment',
    title: 'Service Crash in Payment Service',
    targetService: 'Payment Service',
    category: 'Process Crash',
    description: 'Uncaught null pointer exception on malformed transaction payloads triggers unexpected process termination and 503 cascading failures.',
    telemetrySignatures: ['Payment Health 0.0', 'Restart count +3', 'HTTP 503 error rate 78%', 'Order checkout failures'],
    expectedTopRootCause: 'Payment Service process crash from unhandled exception in settlement worker',
    recommendedPlaybook: 'Automatic Container Restart & Circuit Breaker',
    safeRecoveryAction: 'Restart crashed container with isolated sandbox fallback',
  },
  {
    id: 'network_latency_inventory',
    title: 'Network Latency / Packet Delay to Inventory',
    targetService: 'Inventory Service',
    category: 'Network Partition / Delay',
    description: 'Simulated inter-service network congestion and packet jitter causes 1200ms roundtrip delay on stock check RPCs, blocking checkout flow.',
    telemetrySignatures: ['Inventory RPC latency 1250ms', 'Local host CPU normal (18%)', 'Order checkout timeouts', 'TCP retransmits +42%'],
    expectedTopRootCause: 'Network path latency & packet delay on Inventory Service RPC channel',
    recommendedPlaybook: 'Activate Local Stock Cache & Request Hedging',
    safeRecoveryAction: 'Switch to read-only stock cache fallback mode',
  },
  {
    id: 'slow_payment_gateway',
    title: 'Slow External Payment Gateway',
    targetService: 'Payment Service (Downstream)',
    category: 'External Dependency',
    description: 'Third-party simulated payment clearing gateway experiences a 4500ms delay, blocking Payment Service threads and stalling upstream Order checkout.',
    telemetrySignatures: ['External Gateway latency 4600ms', 'Payment thread queue saturated', 'Downstream correlation 0.94'],
    expectedTopRootCause: 'Downstream external payment gateway clearing latency timeout',
    recommendedPlaybook: 'Enable Async Payment Webhook Processing & Circuit Breaker',
    safeRecoveryAction: 'Engage gateway circuit breaker and async queue fallback',
  },
  {
    id: 'cascading_failure_chain',
    title: 'Cascading Multi-Service Overload',
    targetService: 'Order -> Payment -> Inventory -> Notification',
    category: 'Cascading Cascade',
    description: 'Initial order overload triggers retry storms that propagate to Payment, Inventory, and Notification services, saturating the entire cluster.',
    telemetrySignatures: ['All 4 downstream services degraded', 'Error rate chain propagation: Order(28%) -> Pay(34%) -> Inv(22%)', 'Cluster-wide queue backup'],
    expectedTopRootCause: 'Uncontrolled retry storm originating from Order Service upstream failure',
    recommendedPlaybook: 'Cluster Rate Limiting & Aggressive Circuit Breaking',
    safeRecoveryAction: 'Apply global token-bucket rate limiter & trip retry breakers',
  },
];

export const INITIAL_SERVICES: Microservice[] = [
  {
    id: 'user-service',
    name: 'User Service',
    version: 'v2.4.1',
    status: 'healthy',
    instanceCount: 3,
    uptimeSeconds: 84200,
    description: 'Handles user authentication, JWT session verification, and user profile management.',
    language: 'TypeScript / Node.js',
    framework: 'Express',
    database: 'PostgreSQL (users_db)',
    endpoints: [
      { method: 'POST', path: '/api/v1/auth/login', description: 'User login & session token creation', avgLatencyMs: 24 },
      { method: 'GET', path: '/api/v1/users/{id}', description: 'Fetch user profile & preferences', avgLatencyMs: 18 },
      { method: 'GET', path: '/health', description: 'Liveness & readiness probe', avgLatencyMs: 4 },
    ],
    currentMetrics: {
      cpuPercent: 22,
      memoryMb: 320,
      memoryMaxMb: 1024,
      requestRate: 85,
      latencyP50Ms: 16,
      latencyP95Ms: 38,
      latencyP99Ms: 72,
      errorRatePercent: 0.1,
      dbQueryLatencyMs: 8,
      dbConnectionsActive: 12,
      dbConnectionsMax: 50,
      restartCount: 0,
    },
  },
  {
    id: 'order-service',
    name: 'Order Service',
    version: 'v3.1.0',
    status: 'healthy',
    instanceCount: 4,
    uptimeSeconds: 91400,
    description: 'Core checkout orchestrator. Coordinates with User, Payment, Inventory, and Notification services.',
    language: 'Java / Kotlin',
    framework: 'Spring Boot',
    database: 'PostgreSQL (orders_db)',
    endpoints: [
      { method: 'POST', path: '/api/v1/orders', description: 'Initiate and orchestrate new order checkout', avgLatencyMs: 42 },
      { method: 'GET', path: '/api/v1/orders/{id}', description: 'Fetch order status and order items', avgLatencyMs: 22 },
      { method: 'GET', path: '/health', description: 'Liveness probe & downstream dependency check', avgLatencyMs: 6 },
    ],
    currentMetrics: {
      cpuPercent: 28,
      memoryMb: 580,
      memoryMaxMb: 2048,
      requestRate: 140,
      latencyP50Ms: 28,
      latencyP95Ms: 52,
      latencyP99Ms: 95,
      errorRatePercent: 0.2,
      dbQueryLatencyMs: 14,
      dbConnectionsActive: 22,
      dbConnectionsMax: 100,
      queueBacklog: 8,
      restartCount: 0,
    },
  },
  {
    id: 'payment-service',
    name: 'Payment Service',
    version: 'v1.8.2',
    status: 'healthy',
    instanceCount: 3,
    uptimeSeconds: 112000,
    description: 'Processes credit card transactions, fraud checks, and downstream gateway settlements.',
    language: 'Go',
    framework: 'Gin',
    database: 'PostgreSQL (payments_db)',
    endpoints: [
      { method: 'POST', path: '/api/v1/payments/charge', description: 'Authorize and capture payment charge', avgLatencyMs: 48 },
      { method: 'GET', path: '/api/v1/payments/{id}', description: 'Query transaction reconciliation state', avgLatencyMs: 15 },
      { method: 'GET', path: '/health', description: 'Health check & gateway connectivity', avgLatencyMs: 5 },
    ],
    currentMetrics: {
      cpuPercent: 19,
      memoryMb: 210,
      memoryMaxMb: 1024,
      requestRate: 65,
      latencyP50Ms: 32,
      latencyP95Ms: 58,
      latencyP99Ms: 110,
      errorRatePercent: 0.1,
      dbQueryLatencyMs: 11,
      dbConnectionsActive: 16,
      dbConnectionsMax: 80,
      restartCount: 0,
    },
  },
  {
    id: 'inventory-service',
    name: 'Inventory Service',
    version: 'v2.0.4',
    status: 'healthy',
    instanceCount: 3,
    uptimeSeconds: 78000,
    description: 'Tracks product stock quantities, handles reservations, and validates warehouse availability.',
    language: 'Python',
    framework: 'FastAPI',
    database: 'PostgreSQL (inventory_db)',
    endpoints: [
      { method: 'GET', path: '/api/v1/inventory/{sku}', description: 'Check real-time stock balance', avgLatencyMs: 14 },
      { method: 'POST', path: '/api/v1/inventory/reserve', description: 'Reserve stock units during checkout lock', avgLatencyMs: 26 },
      { method: 'GET', path: '/health', description: 'Liveness and cache health', avgLatencyMs: 3 },
    ],
    currentMetrics: {
      cpuPercent: 18,
      memoryMb: 260,
      memoryMaxMb: 1024,
      requestRate: 110,
      latencyP50Ms: 14,
      latencyP95Ms: 32,
      latencyP99Ms: 64,
      errorRatePercent: 0.05,
      dbQueryLatencyMs: 9,
      dbConnectionsActive: 14,
      dbConnectionsMax: 60,
      restartCount: 0,
    },
  },
  {
    id: 'notification-service',
    name: 'Notification Service',
    version: 'v1.5.0',
    status: 'healthy',
    instanceCount: 2,
    uptimeSeconds: 140000,
    description: 'Asynchronously delivers order confirmation emails, push notifications, and SMS receipts.',
    language: 'Node.js',
    framework: 'NestJS',
    database: 'Redis / Message Queue',
    endpoints: [
      { method: 'POST', path: '/api/v1/notify/email', description: 'Send transactional order email', avgLatencyMs: 35 },
      { method: 'POST', path: '/api/v1/notify/sms', description: 'Send SMS shipping alert', avgLatencyMs: 40 },
      { method: 'GET', path: '/health', description: 'Health & queue connectivity', avgLatencyMs: 4 },
    ],
    currentMetrics: {
      cpuPercent: 12,
      memoryMb: 180,
      memoryMaxMb: 512,
      requestRate: 45,
      latencyP50Ms: 20,
      latencyP95Ms: 42,
      latencyP99Ms: 80,
      errorRatePercent: 0.05,
      dbQueryLatencyMs: 5,
      dbConnectionsActive: 6,
      dbConnectionsMax: 30,
      queueBacklog: 2,
      restartCount: 0,
    },
  },
];

export const INITIAL_DEPENDENCIES: ServiceDependency[] = [
  {
    id: 'dep-order-user',
    sourceServiceId: 'order-service',
    targetServiceId: 'user-service',
    sourceName: 'Order Service',
    targetName: 'User Service',
    dependencyType: 'http',
    endpoint: '/api/v1/users/{id}',
    avgLatencyMs: 18,
    callRatePerMin: 840,
    failureRatePercent: 0.1,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-order-payment',
    sourceServiceId: 'order-service',
    targetServiceId: 'payment-service',
    sourceName: 'Order Service',
    targetName: 'Payment Service',
    dependencyType: 'http',
    endpoint: '/api/v1/payments/charge',
    avgLatencyMs: 48,
    callRatePerMin: 520,
    failureRatePercent: 0.2,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-order-inventory',
    sourceServiceId: 'order-service',
    targetServiceId: 'inventory-service',
    sourceName: 'Order Service',
    targetName: 'Inventory Service',
    dependencyType: 'http',
    endpoint: '/api/v1/inventory/reserve',
    avgLatencyMs: 26,
    callRatePerMin: 780,
    failureRatePercent: 0.05,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-order-notification',
    sourceServiceId: 'order-service',
    targetServiceId: 'notification-service',
    sourceName: 'Order Service',
    targetName: 'Notification Service',
    dependencyType: 'queue',
    endpoint: '/api/v1/notify/email',
    avgLatencyMs: 35,
    callRatePerMin: 420,
    failureRatePercent: 0.1,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-order-db',
    sourceServiceId: 'order-service',
    targetServiceId: 'postgres-db',
    sourceName: 'Order Service',
    targetName: 'PostgreSQL (orders_db)',
    dependencyType: 'database',
    endpoint: 'TCP:5432/orders_db',
    avgLatencyMs: 14,
    callRatePerMin: 1200,
    failureRatePercent: 0.0,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-user-db',
    sourceServiceId: 'user-service',
    targetServiceId: 'postgres-db',
    sourceName: 'User Service',
    targetName: 'PostgreSQL (users_db)',
    dependencyType: 'database',
    endpoint: 'TCP:5432/users_db',
    avgLatencyMs: 8,
    callRatePerMin: 950,
    failureRatePercent: 0.0,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-payment-db',
    sourceServiceId: 'payment-service',
    targetServiceId: 'postgres-db',
    sourceName: 'Payment Service',
    targetName: 'PostgreSQL (payments_db)',
    dependencyType: 'database',
    endpoint: 'TCP:5432/payments_db',
    avgLatencyMs: 11,
    callRatePerMin: 610,
    failureRatePercent: 0.0,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-payment-gateway',
    sourceServiceId: 'payment-service',
    targetServiceId: 'ext-gateway',
    sourceName: 'Payment Service',
    targetName: 'Stripe/Visa Gateway Sim',
    dependencyType: 'external_gateway',
    endpoint: 'https://api.gateway-sim.net/v1/charges',
    avgLatencyMs: 65,
    callRatePerMin: 520,
    failureRatePercent: 0.1,
    isImpacted: false,
    status: 'normal',
  },
  {
    id: 'dep-inventory-db',
    sourceServiceId: 'inventory-service',
    targetServiceId: 'postgres-db',
    sourceName: 'Inventory Service',
    targetName: 'PostgreSQL (inventory_db)',
    dependencyType: 'database',
    endpoint: 'TCP:5432/inventory_db',
    avgLatencyMs: 9,
    callRatePerMin: 880,
    failureRatePercent: 0.0,
    isImpacted: false,
    status: 'normal',
  },
];

export const REMEDIATION_PLAYBOOKS: RemediationPlaybook[] = [
  {
    id: 'pb-cpu-scale',
    failureType: 'cpu_saturation',
    rootCauseType: 'compute_overload',
    title: 'Scale Out Service & Enable Request Throttling',
    recommendationText: 'Increase active container replicas by +1 to distribute computation load, and activate non-blocking rate limiter to prevent thread starvation.',
    actionType: 'scale_out_replica',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 25,
    steps: [
      'Provision +1 replica pod in deployment cluster',
      'Verify container health check returns HTTP 200 within 15s',
      'Rebalance traffic ingress via load balancer weights',
      'Confirm CPU utilization drops below 40% threshold',
    ],
  },
  {
    id: 'pb-mem-restart',
    failureType: 'memory_leak',
    rootCauseType: 'heap_exhaustion',
    title: 'Graceful Instance Rolling Restart & Cache Eviction',
    recommendationText: 'Trigger an in-place rolling restart of the affected service instance to reclaim accumulated memory, followed by an immediate cache flush.',
    actionType: 'restart_service',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 20,
    steps: [
      'Drain ongoing HTTP connections on target instance',
      'Signal SIGTERM to Node/Java runtime with 10s graceful termination timeout',
      'Launch fresh replacement container with clean memory footprint',
      'Purge corrupted session token cache keys',
      'Verify memory consumption stabilizes under 350MB',
    ],
  },
  {
    id: 'pb-db-index',
    failureType: 'database_latency',
    rootCauseType: 'missing_sql_index',
    title: 'Deploy Read Cache & Create Composite Query Index',
    recommendationText: 'Activate Redis micro-cache for hot order queries to bypass database pressure immediately, and trigger background non-blocking index creation.',
    actionType: 'optimize_query_index',
    category: 'manual_operational',
    safeAutoAction: false,
    approvalRequired: true,
    priority: 'P2',
    estimatedRecoveryTimeSec: 45,
    steps: [
      'Inject query cache proxy middleware for repeat GET requests',
      'Execute: CREATE INDEX CONCURRENTLY idx_orders_user_status ON orders(user_id, status)',
      'Analyze query execution plan (EXPLAIN ANALYZE) to verify index scan',
      'Monitor DB CPU utilization returning below 30%',
    ],
  },
  {
    id: 'pb-pool-resize',
    failureType: 'db_connection_exhaustion',
    rootCauseType: 'connection_leak',
    title: 'Force-Recycle Leaked Connections & Expand Pool Headroom',
    recommendationText: 'Terminate abandoned transaction connections exceeding 30s timeout and temporarily increase connection pool capacity from 80 to 120.',
    actionType: 'increase_db_pool',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 15,
    steps: [
      'Issue pg_terminate_backend on idle transactions in active state > 30s',
      'Dynamically update HikariCP / DB pool max connections to 120',
      'Patch connection leak in transaction defer block',
      'Verify active connection count drops back to normal operational range (15-25)',
    ],
  },
  {
    id: 'pb-crash-recover',
    failureType: 'service_crash',
    rootCauseType: 'unhandled_runtime_exception',
    title: 'Immediate Container Spin-up & Circuit Breaker Engagement',
    recommendationText: 'Immediately launch fresh container instance and trip upstream circuit breaker with fallback responses to isolate client 500 errors.',
    actionType: 'restart_service',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 12,
    steps: [
      'Orchestrator immediately re-spawns dead container instance',
      'Trip circuit breaker on Order Service calling Payment Service with 60s half-open trial',
      'Ingest core dump and crash stack trace to diagnostics repository',
      'Verify service returns HTTP 200 on /health probe',
    ],
  },
  {
    id: 'pb-net-cache',
    failureType: 'network_latency',
    rootCauseType: 'network_degradation',
    title: 'Enable Local Resilience Cache & Request Hedging',
    recommendationText: 'Switch dependent callers to high-availability local stock cache fallback with hedged duplicate requests at 50ms delay.',
    actionType: 'enable_circuit_breaker',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P2',
    estimatedRecoveryTimeSec: 18,
    steps: [
      'Toggle fallback mode in Order Service to read inventory from local cache layer',
      'Apply hedged request timeout at 120ms to bypass delayed network packets',
      'Notify network operations of inter-subnet jitter',
      'Verify order checkout latency drops from 1200ms to < 45ms',
    ],
  },
  {
    id: 'pb-gateway-breaker',
    failureType: 'external_gateway_timeout',
    rootCauseType: 'downstream_partner_timeout',
    title: 'Engage Payment Circuit Breaker & Asynchronous Clearing',
    recommendationText: 'Trip circuit breaker on slow payment gateway and divert non-critical transactions to asynchronous retry queue.',
    actionType: 'enable_circuit_breaker',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 15,
    steps: [
      'Engage Circuit Breaker for Stripe/Visa Gateway simulator (Open State)',
      'Queue payment transactions to dead-letter / async queue with webhook callback',
      'Return immediate 202 ACCEPTED with status "PENDING_VERIFICATION" to checkout flow',
      'Monitor gateway recovery via periodic synthetic canary pings',
    ],
  },
  {
    id: 'pb-cascade-throttle',
    failureType: 'cascading_failure',
    rootCauseType: 'retry_storm_propagation',
    title: 'Apply Cluster-Wide Token Bucket Throttling & Trip Retry Breakers',
    recommendationText: 'Shed 40% non-essential background traffic, disable exponential retry storms, and prioritize core user checkout paths.',
    actionType: 'throttle_requests',
    category: 'automated_safe',
    safeAutoAction: true,
    approvalRequired: true,
    priority: 'P1',
    estimatedRecoveryTimeSec: 30,
    steps: [
      'Enable token bucket rate limiting on Ingress Gateway (limit 250 req/s)',
      'Trip retry breaker to cap max retries to 0 across inter-service HTTP calls',
      'Divert background notifications to deferred batch queue',
      'Verify latency drops across all downstream services',
    ],
  },
];
